# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Staging

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

jobs:
  build:
    environment: Staging
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:

    - name: SSH Remote Commands
  # You may pin to the exact commit or the version.
  # uses: appleboy/ssh-action@f9010ff7f1bbd7db1a0b4bab661437550cea20c0
      uses: appleboy/ssh-action@v0.1.5
      env:
        USERNAME: ${{secrets.MERXER_USERNAME}}
        HOST: ${{secrets.HOST}}
        PORT: ${{secrets.PORT}}
        DB_NAME: ${{secrets.DB_NAME}}
        DB_HOST: ${{secrets.DB_HOST}}
        BASE: ${{secrets.BASE}}
        SECRET: ${{secrets.SECRET}}
        SALT_ROUNDS: ${{secrets.SALT_ROUNDS}}
        DIR: ${{secrets.DIR}}
      with:
        host: ${{secrets.MERXER_IP}}
        username: ${{secrets.MERXER_USERNAME}}
        password: ${{secrets.MERXER_PASSWORD}}
        script: |
          sudo rm -rf "${DIR}"{*,.*}
          
          cd "${DIR}"
          git clone git@github.com:merchedev/merche.dev.git .
          git checkout staging

          chown "${USERNAME}":www-data -R "${DIR}"

          echo 'Creating .env...in... ${pwd}'
          cat <<EOT > "${DIR}".env
          NODE_ENV=staging
          HOST="${HOST}"
          PORT="${PORT}"
          DB_NAME="${DB_NAME}"
          DB_HOST="${DB_HOST}"
          BASE="${BASE}"
          SECRET="${SECRET}"
          SALT_ROUNDS="${SALT_ROUND}"
          EOT

          echo 'Installing packages in... ${pwd}'
          npm i 
          
          echo 'Building app...in... ${pwd}'
          node_modules/.bin/webpack
          
          echo 'Running app...in... ${pwd}'
          pm2 start ecosystem-staging.config.js

          